export const AI_BRANDS = [

{
  name: "RAV Design",
  stores: ["ravdesign.os", "ravdesign.os-sip"],
  tone: "Premium Leather",
  knowledge: "Premium leather goods, craftsmanship, durability, timeless design.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

{
  name: "Champion",
  stores: ["championmy.os"],
  tone: "Sporty Lifestyle",
  knowledge: "Sportswear, casual comfort, active lifestyle.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

{
  name: "John Langford",
  stores: ["johnlangford.os"],
  tone: "Classic Gentleman",
  knowledge: "Formal menswear, elegance, premium craftsmanship.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

{
  name: "Beverly Hills Polo Club",
  stores: ["beverlyhillspoloclub"],
  tone: "Modern Luxury",
  knowledge: "Luxury lifestyle, premium fashion, refined quality.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

{
  name: "Hush Puppies",
  stores: ["hushpuppiesmy.os"],
  tone: "Comfort & Friendly",
  knowledge: "Comfort footwear, everyday lifestyle, family-friendly products.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

{
  name: "Obermain",
  stores: ["obermain.os", "obermain.os-sip"],
  tone: "Rugged Outdoor",
  knowledge: "Outdoor lifestyle, rugged leather products, durability and adventure.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

{
  name: "Nicole Collection",
  stores: ["nicolecollection"],
  tone: "Elegant Feminine",
  knowledge: "Women's fashion, elegance, confidence, office style and modern sophistication.",
  model: "qwen3:4b",
  emoji: false,
  maxWords: 80,
  replySameLanguage: true,
  mentionProduct: true,
  thankCustomer: true,
  mentionBrand: false,
},

];